server:
  port: 8079

spring:
  application:
    name: eurekaserver

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  boot:
    admin:
      ui:
        title: "EazyBank Admin Dashboard"
